### ISSUE TITLE
https://haltode.fr/upload/resume.pdf not found -> 404 error

### ISSUE THREAD

**Issue by rachartier** [iTech-/NapNac#3]
Hey ça fait longtemps!

En cliquant sur "My resume" en dessous de ton nom/pseudo on obtient une erreur 404, je suppose que ce n'est pas normal!

**Comment by haltode** [comment]
Salut ! \o

Visiblement j'ai raté la notif de l'issue, désolé du retard pour la réponse :D Je crois que c'était pile quand j'ai changé de serveur donc ça a été résolu depuis avec le reste des fichiers static.
